import { Michroma } from "next/font/google";
import "./globals.css";

const michroma = Michroma({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Stanley Dix Portfolio",
  description: "Generated by Stanley Dix",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={michroma.className}>{children}</body>
    </html>
  );
}
